backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfolio Projects"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
